global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api"
    static_configs:
      - targets: ["api:8080"]

  - job_name: "assetcache"
    static_configs:
      - targets: ["assetcache:8000"]

  - job_name: "oms"
    static_configs:
      - targets: ["oms:9000"]

  - job_name: "persister"
    dns_sd_configs:
      - names:
          - persister
        type: A
        port: 9001

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]


#        TODO: postgres exporter